# Generated by Django 3.2.5 on 2023-01-18 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0002_availablerecharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesstokens',
            name='wallet_balance',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='availablerecharge',
            name='detail',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('1', 'DU_PREPAID'), ('2', 'DU_POSTPAID')], max_length=100)),
                ('recharge_type', models.CharField(choices=[('1', 'DATA'), ('2', 'MINUTE')], max_length=100)),
                ('recharge_number', models.CharField(max_length=10)),
                ('amount', models.FloatField()),
                ('status', models.CharField(choices=[('1', 'COMPLETED'), ('2', 'PROCESSING'), ('3', 'FAILED')], max_length=100)),
                ('sub_status', models.CharField(choices=[('1', 'PAYMENT_PROCESSING'), ('2', 'PAYMENT_COMPLETED'), ('3', 'PAYMENT_FAILED'), ('4', 'RECHARGE_PROCESSING'), ('5', 'RECHARGE_FAILED'), ('6', 'RECHARGE_COMPLETED')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='MbmeOrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.JSONField()),
                ('transaction_id', models.CharField(max_length=100)),
                ('unique_id', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mbme_history', to='orders.orders')),
            ],
            options={
                'db_table': 'mbme_order_history',
            },
        ),
    ]
