# Generated by Django 3.2.5 on 2023-01-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20230119_0311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('COMPLETED', 'COMPLETED'), ('PROCESSING', 'PROCESSING'), ('FAILED', 'FAILED')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='sub_status',
            field=models.CharField(choices=[('PAYMENT_PROCESSING', 'PAYMENT_PROCESSING'), ('PAYMENT_COMPLETED', 'PAYMENT_COMPLETED'), ('PAYMENT_FAILED', 'PAYMENT_FAILED'), ('RECHARGE_PROCESSING', 'RECHARGE_PROCESSING'), ('RECHARGE_FAILED', 'RECHARGE_FAILED'), ('RECHARGE_COMPLETED', 'RECHARGE_COMPLETED')], max_length=100),
        ),
    ]
