# Generated by Django 3.2.5 on 2023-01-19 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20230119_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('1', 'COMPLETED'), ('2', 'PROCESSING'), ('3', 'FAILED')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='sub_status',
            field=models.CharField(choices=[('1', 'PAYMENT_PROCESSING'), ('2', 'PAYMENT_COMPLETED'), ('3', 'PAYMENT_FAILED'), ('4', 'RECHARGE_PROCESSING'), ('5', 'RECHARGE_FAILED'), ('6', 'RECHARGE_COMPLETED')], max_length=100),
        ),
    ]
