# Generated by Django 3.2.5 on 2023-01-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20230119_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablerecharge',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
