# Generated by Django 3.2.5 on 2023-01-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_availablerecharge_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='MBMEVerifiedCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('1', 'DU_PREPAID'), ('2', 'DU_POSTPAID')], max_length=100)),
                ('recharge_type', models.CharField(choices=[('1', 'DATA'), ('2', 'MINUTE')], max_length=100)),
                ('recharge_number', models.CharField(max_length=10)),
                ('valid_upto', models.DateTimeField()),
            ],
        ),
    ]
