# Generated by Django 3.2.5 on 2023-01-19 21:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0007_mbmeverifiedcustomer'),
    ]

    operations = [
        migrations.CreateModel(
            name='MBMEVerifiedNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('1', 'DU_PREPAID'), ('2', 'DU_POSTPAID')], max_length=100)),
                ('recharge_type', models.CharField(choices=[('1', 'DATA'), ('2', 'MINUTE')], max_length=100)),
                ('recharge_number', models.CharField(max_length=10)),
                ('valid_upto', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mbme_verified_numbers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mbme_verified_numbers',
            },
        ),
        migrations.DeleteModel(
            name='MBMEVerifiedCustomer',
        ),
    ]
