# Generated by Django 3.2.5 on 2023-01-20 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20230120_0327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mbmeverifiednumbers',
            name='user',
        ),
    ]
