# Generated by Django 3.2.5 on 2023-01-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_mbmeverifiednumbers_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='availablerecharge',
            name='full_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='availablerecharge',
            name='validity',
            field=models.CharField(default='30 days', max_length=100),
            preserve_default=False,
        ),
    ]
