# Generated by Django 3.2.5 on 2023-01-20 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20230120_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifiedNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('1', 'DU_PREPAID'), ('2', 'DU_POSTPAID')], max_length=100)),
                ('recharge_type', models.CharField(choices=[('1', 'DATA'), ('2', 'MINUTE')], max_length=100)),
                ('service_provider', models.CharField(choices=[('1', 'MBME')], max_length=100)),
                ('recharge_number', models.CharField(max_length=10)),
                ('valid_upto', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'verified_numbers',
            },
        ),
        migrations.RenameModel(
            old_name='MbmeOrderHistory',
            new_name='OrderHistory',
        ),
        migrations.DeleteModel(
            name='MBMEVerifiedNumbers',
        ),
        migrations.AddField(
            model_name='accesstokens',
            name='service_provider',
            field=models.CharField(choices=[('1', 'MBME')], default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='availablerecharge',
            name='service_provider',
            field=models.CharField(choices=[('1', 'MBME')], default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='service_provider',
            field=models.CharField(choices=[('1', 'MBME')], default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name='orderhistory',
            table='order_history',
        ),
    ]
