# Generated by Django 3.2.5 on 2023-01-20 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_auto_20230120_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_history', to='orders.orders'),
        ),
        migrations.CreateModel(
            name='InProcessOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.JSONField()),
                ('transaction_id', models.CharField(max_length=100)),
                ('unique_id', models.CharField(max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='in_process_orders', to='orders.orders')),
            ],
            options={
                'db_table': 'in_process_order',
            },
        ),
    ]
