# Generated by Django 3.2.5 on 2023-01-20 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_auto_20230121_0235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inprocessorders',
            old_name='response',
            new_name='last_response',
        ),
        migrations.RemoveField(
            model_name='inprocessorders',
            name='transaction_id',
        ),
        migrations.RemoveField(
            model_name='inprocessorders',
            name='unique_id',
        ),
        migrations.AddField(
            model_name='inprocessorders',
            name='retry_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inprocessorders',
            name='sub_status',
            field=models.CharField(choices=[('1', 'PAYMENT_PROCESSING'), ('2', 'PAYMENT_COMPLETED'), ('3', 'PAYMENT_FAILED'), ('4', 'RECHARGE_PROCESSING'), ('5', 'RECHARGE_FAILED'), ('6', 'RECHARGE_COMPLETED')], default='4', max_length=100),
            preserve_default=False,
        ),
    ]
