# Generated by Django 3.2.5 on 2023-01-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_auto_20230121_0247'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inprocessorders',
            name='sub_status',
        ),
        migrations.AddField(
            model_name='inprocessorders',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inprocessorders',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inprocessorders',
            name='unique_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inprocessorders',
            name='last_response',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='OrderHistory',
        ),
    ]
