# Generated by Django 3.2.5 on 2023-01-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20230122_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
