# Generated by Django 3.2.5 on 2023-01-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_orders_updated_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostpaidAccountBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('1', 'DU_PREPAID'), ('2', 'DU_POSTPAID')], max_length=100)),
                ('recharge_type', models.CharField(choices=[('1', 'DATA'), ('2', 'MINUTE')], max_length=100)),
                ('service_provider', models.CharField(choices=[('1', 'MBME')], max_length=100)),
                ('recharge_number', models.CharField(max_length=10)),
                ('valid_upto', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'postpaid_account_balance',
            },
        ),
    ]
