# Generated by Django 3.2.5 on 2023-01-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_postpaidaccountbalance'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpaidaccountbalance',
            name='balance',
            field=models.CharField(default=10, max_length=10),
            preserve_default=False,
        ),
    ]
