# Generated by Django 3.2.5 on 2023-01-23 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_postpaidaccountbalance_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpaidaccountbalance',
            name='response',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
