# Generated by Django 3.2.5 on 2023-01-23 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_postpaidaccountbalance_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpaidaccountbalance',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
