# Generated by Django 3.2.5 on 2023-01-23 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_postpaidaccountbalance_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postpaidaccountbalance',
            name='recharge_type',
            field=models.CharField(blank=True, choices=[('1', 'DATA'), ('2', 'MINUTE')], max_length=100, null=True),
        ),
    ]
