# Generated by Django 3.2.5 on 2023-01-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_alter_postpaidaccountbalance_recharge_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpaidaccountbalance',
            name='recharge_transaction_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
