# Generated by Django 3.2.5 on 2023-01-23 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_postpaidaccountbalance_recharge_transaction_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InProcessOrders',
            new_name='OrdersDetails',
        ),
        migrations.AlterModelTable(
            name='ordersdetails',
            table='orders_details',
        ),
    ]
