# Generated by Django 3.2.5 on 2023-01-23 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_auto_20230124_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersdetails',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_detail', to='orders.orders'),
        ),
    ]
