# Generated by Django 3.2.5 on 2023-01-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_alter_ordersdetails_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_id',
            field=models.CharField(default='ORD1234444444', max_length=500, unique=True),
            preserve_default=False,
        ),
    ]
