# Generated by Django 3.2.5 on 2023-01-30 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_alter_orders_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='verifiednumbers',
            name='is_valid',
            field=models.BooleanField(default=False),
        ),
    ]
