# Generated by Django 3.2.5 on 2023-02-03 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_verifiednumbers_is_valid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProviders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True, null=True)),
                ('service_id', models.CharField(choices=[('1', 'DU_PREPAID'), ('2', 'DU_POSTPAID'), ('3', 'ETISALAT'), ('4', 'HAFILAT'), ('5', 'NOL_TOPUP'), ('6', 'SALIK_DIRECT')], max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
            options={
                'db_table': 'service_providers',
            },
        ),
        migrations.CreateModel(
            name='VerifiedAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('1', 'DU_PREPAID'), ('2', 'DU_POSTPAID'), ('3', 'ETISALAT'), ('4', 'HAFILAT'), ('5', 'NOL_TOPUP'), ('6', 'SALIK_DIRECT')], max_length=100)),
                ('service_provider', models.CharField(choices=[('1', 'MBME')], max_length=100)),
                ('recharge_number', models.CharField(max_length=10)),
                ('is_valid', models.BooleanField(default=False)),
                ('valid_upto', models.DateTimeField()),
                ('response', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'verified_accounts',
            },
        ),
        migrations.DeleteModel(
            name='PostpaidAccountBalance',
        ),
        migrations.DeleteModel(
            name='VerifiedNumbers',
        ),
        migrations.AlterField(
            model_name='availablerecharge',
            name='service_type',
            field=models.CharField(choices=[('1', 'DU_PREPAID'), ('2', 'DU_POSTPAID'), ('3', 'ETISALAT'), ('4', 'HAFILAT'), ('5', 'NOL_TOPUP'), ('6', 'SALIK_DIRECT')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='service_type',
            field=models.CharField(choices=[('1', 'DU_PREPAID'), ('2', 'DU_POSTPAID'), ('3', 'ETISALAT'), ('4', 'HAFILAT'), ('5', 'NOL_TOPUP'), ('6', 'SALIK_DIRECT')], max_length=100),
        ),
    ]
