# Generated by Django 3.2.5 on 2023-02-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_auto_20230204_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablerecharge',
            name='service_type',
            field=models.CharField(choices=[('1', 'DU_PREPAID'), ('2', 'DU_POSTPAID'), ('4', 'ETISALAT'), ('5', 'HAFILAT'), ('3', 'NOL_TOPUP'), ('6', 'SALIK_DIRECT')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='service_type',
            field=models.CharField(choices=[('1', 'DU_PREPAID'), ('2', 'DU_POSTPAID'), ('4', 'ETISALAT'), ('5', 'HAFILAT'), ('3', 'NOL_TOPUP'), ('6', 'SALIK_DIRECT')], max_length=100),
        ),
        migrations.AlterField(
            model_name='serviceproviders',
            name='service_id',
            field=models.CharField(choices=[('1', 'DU_PREPAID'), ('2', 'DU_POSTPAID'), ('4', 'ETISALAT'), ('5', 'HAFILAT'), ('3', 'NOL_TOPUP'), ('6', 'SALIK_DIRECT')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='verifiedaccounts',
            name='service_type',
            field=models.CharField(choices=[('1', 'DU_PREPAID'), ('2', 'DU_POSTPAID'), ('4', 'ETISALAT'), ('5', 'HAFILAT'), ('3', 'NOL_TOPUP'), ('6', 'SALIK_DIRECT')], max_length=100),
        ),
    ]
