# Generated by Django 3.2.5 on 2023-02-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_auto_20230205_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablerecharge',
            name='recharge_type',
            field=models.CharField(choices=[('1', 'DATA'), ('2', 'MINUTE'), ('3', '3'), ('4', '4')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='recharge_type',
            field=models.CharField(choices=[('1', 'DATA'), ('2', 'MINUTE'), ('3', '3'), ('4', '4')], max_length=100),
        ),
    ]
