# Generated by Django 3.2.5 on 2023-02-07 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_auto_20230208_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availablerecharge',
            name='recharge_type',
            field=models.CharField(choices=[('1', 'DATA'), ('2', 'MINUTE'), ('3', 'HAFILAT_T_PURSE'), ('4', 'HAFILAT_PASS')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='recharge_type',
            field=models.CharField(choices=[('1', 'DATA'), ('2', 'MINUTE'), ('3', 'HAFILAT_T_PURSE'), ('4', 'HAFILAT_PASS')], max_length=100),
        ),
        migrations.AlterField(
            model_name='verifiedaccounts',
            name='recharge_number',
            field=models.CharField(max_length=30),
        ),
    ]
