# Generated by Django 3.2.5 on 2023-02-07 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_auto_20230208_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='recharge_number',
            field=models.CharField(max_length=30),
        ),
    ]
