# Generated by Django 3.2.5 on 2021-12-31 08:57

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='news_keyword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(default='', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('radius', models.IntegerField(default=0)),
                ('lat', models.CharField(max_length=30)),
                ('lng', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserReguest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('service_provider', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('status', models.CharField(default='Pending', max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('code', models.CharField(blank=True, default='', max_length=5, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('sampledate', models.DateTimeField(auto_now_add=True, null=True)),
                ('image', models.ImageField(blank=True, default='noimage.png', null=True, upload_to='Profile')),
                ('role', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(default='', max_length=50)),
                ('state', models.CharField(default='', max_length=50)),
                ('city', models.CharField(default='', max_length=50)),
                ('device_type', models.CharField(blank=True, default='', max_length=10, null=True)),
                ('device_token', models.CharField(blank=True, max_length=500, null=True)),
                ('referral_code', models.CharField(blank=True, max_length=100, null=True)),
                ('isotp_verified', models.BooleanField(default=False)),
                ('is_profile_complete', models.BooleanField(default=False)),
                ('is_subadmin', models.BooleanField(default=False)),
                ('location', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserCreditPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_points', models.IntegerField(default=0)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_points', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SubAdminPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dashboard', models.BooleanField(default=False)),
                ('user_mgmt', models.BooleanField(default=False)),
                ('subadmin_mgmt', models.BooleanField(default=False)),
                ('geolocation_mgmt', models.BooleanField(default=False)),
                ('order_mgmt_per', models.BooleanField(default=False)),
                ('chats_mgmt', models.BooleanField(default=False)),
                ('news_mgmt', models.BooleanField(default=False)),
                ('lottery_mgmt', models.BooleanField(default=False)),
                ('payment_mgmt', models.BooleanField(default=False)),
                ('credit_pts_mgmt', models.BooleanField(default=False)),
                ('promotion_mgmt', models.BooleanField(default=False)),
                ('issue_mgmt', models.BooleanField(default=False)),
                ('notification_mgmt', models.BooleanField(default=False)),
                ('social_media_mgmt', models.BooleanField(default=False)),
                ('report_mgmt', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sub_admin_permission', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='state',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.country')),
            ],
        ),
        migrations.CreateModel(
            name='signup_otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(blank=True, max_length=10)),
                ('expire', models.DateTimeField(null=True)),
                ('attempt', models.IntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='savecountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('state', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=30, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block', models.BooleanField(default=False)),
                ('title', models.CharField(default='', max_length=1000)),
                ('author', models.CharField(default='', max_length=1000)),
                ('description', models.TextField()),
                ('publishedAt', models.DateTimeField(null=True)),
                ('content', models.TextField(null=True)),
                ('url', models.TextField(null=True)),
                ('urlToImage', models.CharField(default='', max_length=10000, null=True)),
                ('keyword', models.CharField(default='', max_length=1000)),
                ('when_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LikeNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like_date', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.news')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='forget_otp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(blank=True, max_length=10)),
                ('expire', models.DateTimeField(null=True)),
                ('secret_key', models.CharField(default='', max_length=50)),
                ('attempt', models.IntegerField(default=0)),
                ('is_used', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreditPointTransaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('reason_title', models.CharField(default='', max_length=100)),
                ('reason_desc', models.TextField(blank=True, null=True)),
                ('order_id', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('referral_id', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('debited_points', models.IntegerField(default=0)),
                ('credited_points', models.IntegerField(default=0)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommentNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.TextField()),
                ('comment_date', models.DateTimeField(auto_now_add=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.news')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.state')),
            ],
        ),
    ]
