# Generated by Django 3.2.5 on 2022-01-03 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_bio',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
