# Generated by Django 3.2.5 on 2022-05-24 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userprofile_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='quickblox_id',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
