# Generated by Django 3.2.5 on 2023-01-11 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_chatgroupadmin_chatgroupmember_userchat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatgroupmember',
            name='chat_group',
        ),
        migrations.RemoveField(
            model_name='chatgroupmember',
            name='member',
        ),
        migrations.RemoveField(
            model_name='creditpointtransaction',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userchat',
            name='chat_group',
        ),
        migrations.RemoveField(
            model_name='userchat',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='userchat',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='usercreditpoint',
            name='user',
        ),
        migrations.DeleteModel(
            name='ChatGroupAdmin',
        ),
        migrations.DeleteModel(
            name='ChatGroupMember',
        ),
        migrations.DeleteModel(
            name='CreditPointTransaction',
        ),
        migrations.DeleteModel(
            name='UserChat',
        ),
        migrations.DeleteModel(
            name='UserCreditPoint',
        ),
    ]
