# Generated by Django 3.2.5 on 2023-02-17 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_savecountry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='country_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.country'),
            preserve_default=False,
        ),
    ]
