# Generated by Django 3.2.5 on 2023-02-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_city_country_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='state',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
