# Generated by Django 3.2.5 on 2023-04-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20230423_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, default='profile/no-image.png', null=True, upload_to='Profile'),
        ),
    ]
