# Generated by Django 3.2.5 on 2023-05-09 11:22

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0012_userprofile_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=70)),
                ('last_name', models.CharField(blank=True, max_length=70, null=True)),
                ('email', models.CharField(max_length=200)),
                ('Account_id', models.CharField(default='', max_length=20)),
                ('user_type', models.CharField(choices=[('0', 'Normal'), ('1', 'Admin'), ('2', 'SubAdmin'), ('3', 'IndividualRestaurant'), ('4', 'Supplier'), ('5', 'ProcurementOfficer')], max_length=10)),
                ('gender', models.CharField(choices=[('1', 'MALE'), ('2', 'FEMALE'), ('3', 'OTHER'), ('4', 'Not Selected')], max_length=10)),
                ('country_code', models.CharField(blank=True, max_length=5, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('mobile_number', models.CharField(default='', max_length=15)),
                ('account_type', models.CharField(choices=[('1', 'normal'), ('2', 'google'), ('3', 'twitter'), ('4', 'apple')], max_length=10)),
                ('device_type', models.CharField(choices=[('1', 'android'), ('2', 'ios'), ('3', 'web')], max_length=10)),
                ('profile_image', models.ImageField(default='User/profile_image/default.jpg', null=True, upload_to='User/profile_image')),
                ('allergic_to', models.CharField(blank=True, default='None', max_length=500, null=True)),
                ('is_block', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('location', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326)),
                ('when_add', models.DateTimeField(auto_now_add=True)),
                ('loyalty_points', models.IntegerField(default=0)),
                ('device_token', models.CharField(blank=True, max_length=200, null=True)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
