# Generated by Django 3.2.5 on 2023-05-11 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_useraccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='signup_type',
            field=models.CharField(default='1', max_length=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='socialsignup_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
