# Generated by Django 3.2.5 on 2023-05-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_useraccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='social_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
