# Generated by Django 3.2.5 on 2023-05-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_auto_20230511_1403'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('1', 'Normal'), ('2', 'Admin')], default=1, max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='signup_type',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
