class GeneratetokenSerializer(Serializer):
    first_name = CharField(error_messages={'required':'First name is required', 'blank':'first name is required'},max_length=400)
    last_name = CharField(error_messages={'required':'Last name is required', 'blank':'last name is required'},max_length=400)
    mobile_number = CharField(error_messages={'required':'mobile number is required', 'blank':'mobile number is required'},max_length=20)
    email = EmailField(max_length=400)
    #nationality = CharField(error_messages={'required':'nationality is required', 'blank':'nationality is required'},max_length=400)
    #gender = CharField(error_messages={'required':'Gender is required', 'blank':'Gender is required'},max_length=100)
    password=CharField(error_messages={'required':'password is required', 'blank':'password is required'})
    device_token=CharField(error_messages={'required':'device_token is required', 'blank':'device_token is required'},max_length=5000)
    device_type=CharField(error_messages={'required':'device_type is required', 'blank':'device_type is required'},max_length=10)
    code=CharField(error_messages={'required':'Country code is required','blank':'Country code is required'},max_length=100)
    latitude=FloatField(error_messages={'required':'latitude is required','blank':'latitude is required'},min_value=0.0)
    longitude=FloatField(error_messages={'required':'longitude is required','blank':'longitude is required'},min_value=0.0)
    #dob=CharField(required=False,allow_blank=True)
    referral_code=CharField(required=False,allow_blank=True)
    #user_bio=CharField(required=False,allow_blank=True)
    