# Generated by Django 3.2.5 on 2023-04-23 13:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_backup', models.CharField(choices=[('1', 'GOOGLE_DRIVE'), ('2', 'GOOGLE_ACCOUNT'), ('3', 'WIFI')], max_length=50)),
                ('font_size', models.CharField(choices=[('1', 'SMALL'), ('2', 'MEDIUM'), ('3', 'LARGE')], max_length=50)),
                ('media_visibility', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_settings',
            },
        ),
    ]
