# Generated by Django 3.2.5 on 2023-04-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsettings',
            name='chat_backup',
            field=models.CharField(choices=[('1', 'GOOGLE_DRIVE'), ('2', 'GOOGLE_ACCOUNT'), ('3', 'WIFI')], default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='chatsettings',
            name='font_size',
            field=models.CharField(choices=[('1', 'SMALL'), ('2', 'MEDIUM'), ('3', 'LARGE')], default='2', max_length=50),
        ),
    ]
