# Generated by Django 3.2.5 on 2023-05-01 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notification', '0005_notification_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='UserNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('desc', models.TextField()),
                ('order_service_type', models.CharField(blank=True, choices=[('1', 'DU_PREPAID'), ('2', 'DU_POSTPAID'), ('3', 'ETISALAT'), ('5', 'HAFILAT'), ('4', 'NOL_TOPUP'), ('6', 'SALIK_DIRECT')], max_length=100, null=True)),
                ('notification_type', models.CharField(choices=[('1', 'ORDER_SERVICE_NOTIFICATION'), ('2', 'BROADCAST_NOTIFICATION')], max_length=100)),
                ('is_send', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('seen_at', models.DateTimeField(blank=True, null=True)),
                ('is_seen', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_notification', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='notification.notification')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_notification', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_notification',
            },
        ),
    ]
