# Generated by Django 3.2.5 on 2023-03-22 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquery',
            name='status',
            field=models.CharField(choices=[('1', 'open'), ('2', 'closed')], default='1', max_length=2),
        ),
    ]
