# Generated by Django 3.2.5 on 2023-03-22 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('issues', '0002_userquery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userquery',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_query', to=settings.AUTH_USER_MODEL),
        ),
    ]
