# Generated by Django 3.2.5 on 2023-03-25 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_alter_userquery_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userquery',
            table='user_query',
        ),
    ]
