# Generated by Django 3.2.5 on 2023-04-11 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_alter_userquery_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquery',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
