# Generated by Django 3.2.5 on 2023-01-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField()),
                ('description', models.TextField()),
                ('cms_type', models.CharField(choices=[(1, 'document'), (2, 'policies'), (3, 'faq')], max_length=28)),
                ('policy_type', models.CharField(choices=[(1, 'user'), (2, 'seller')], max_length=28)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
