# Generated by Django 3.2.5 on 2023-01-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cms',
            name='cms_type',
            field=models.CharField(choices=[('1', 'document'), ('2', 'policies'), ('3', 'faq')], max_length=28),
        ),
        migrations.AlterField(
            model_name='cms',
            name='policy_type',
            field=models.CharField(blank=True, choices=[('1', 'user'), ('2', 'seller')], max_length=28),
        ),
    ]
