# Generated by Django 3.2.5 on 2023-04-05 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_auto_20230120_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cms',
            name='policy_type',
        ),
        migrations.AlterField(
            model_name='cms',
            name='cms_type',
            field=models.CharField(choices=[('1', 'TERMS_AND_COND'), ('2', 'PRIVACY_POLICIES'), ('3', 'FAQ'), ('4', 'ABOUT_US'), ('3', 'FAQ')], max_length=28),
        ),
    ]
