# Generated by Django 3.2.5 on 2023-04-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_auto_20230405_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cms',
            name='heading',
            field=models.TextField(blank=True),
        ),
    ]
