# Generated by Django 3.2.5 on 2023-04-05 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_alter_cms_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cms',
            name='cms_type',
            field=models.CharField(choices=[('1', 'TERMS_AND_COND'), ('2', 'PRIVACY_POLICIES'), ('3', 'FAQ'), ('4', 'ABOUT_US'), ('5', 'CONTACT_US')], max_length=28),
        ),
    ]
