# Generated by Django 3.2.5 on 2023-04-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0005_alter_cms_cms_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cms',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
