# Generated by Django 3.2.5 on 2022-06-17 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCreditPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_points', models.IntegerField(default=0)),
                ('updated_on', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user_points', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CreditPointTransaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('reason_title', models.CharField(default='', max_length=100)),
                ('reason_desc', models.TextField(blank=True, null=True)),
                ('order_id', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('referral_id', models.CharField(blank=True, default=None, max_length=10, null=True)),
                ('debited_points', models.IntegerField(default=0)),
                ('credited_points', models.IntegerField(default=0)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
