# Generated by Django 3.2.5 on 2023-01-18 21:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20230119_0311'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0002_stripecustomer'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_intent', models.CharField(max_length=500)),
                ('gateway_response', models.TextField()),
                ('status', models.CharField(choices=[('1', 'PROCESSING'), ('2', 'FAILED'), ('3', 'COMPLETED'), ('4', 'CANCELLED')], max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.orders')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_payment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
