# Generated by Django 3.2.5 on 2023-01-22 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_stripetransactions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stripetransactions',
            old_name='order_id',
            new_name='order',
        ),
    ]
