# Generated by Django 3.2.5 on 2023-01-23 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_alter_orders_updated_on'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payment', '0004_rename_order_id_stripetransactions_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_provide', models.CharField(choices=[('1', 'STRIPE'), ('2', 'PAYPAL')], max_length=50)),
                ('payment_intent', models.CharField(max_length=500)),
                ('gateway_response', models.TextField()),
                ('status', models.CharField(choices=[('1', 'PROCESSING'), ('2', 'FAILED'), ('3', 'COMPLETED'), ('4', 'CANCELLED')], max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='orders.orders')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_payment', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_transactions',
            },
        ),
        migrations.AlterModelTable(
            name='stripecustomer',
            table='stripe_customer',
        ),
        migrations.DeleteModel(
            name='StripeTransactions',
        ),
    ]
