# Generated by Django 3.2.5 on 2023-01-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_auto_20230123_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransactions',
            name='credit_transaction_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransactions',
            name='payment_method',
            field=models.CharField(choices=[('1', 'DEBIT_CARD'), ('2', 'CREDIT_CARD'), ('3', 'APPLE_PAY')], default='1', max_length=50),
            preserve_default=False,
        ),
    ]
