# Generated by Django 3.2.5 on 2023-01-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_auto_20230123_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransactions',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('1', 'DEBIT_CARD'), ('2', 'CREDIT_CARD'), ('3', 'APPLE_PAY')], max_length=50, null=True),
        ),
    ]
