# Generated by Django 3.2.5 on 2023-01-23 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_alter_paymenttransactions_payment_method'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenttransactions',
            old_name='credit_transaction_id',
            new_name='credit_point_transaction_id',
        ),
    ]
