# Generated by Django 3.2.5 on 2023-01-25 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_rename_credit_transaction_id_paymenttransactions_credit_point_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransactions',
            name='transaction_id',
            field=models.CharField(default='TSN28282882', max_length=500, unique=True),
            preserve_default=False,
        ),
    ]
