# Generated by Django 3.2.5 on 2023-01-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0009_paymenttransactions_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenttransactions',
            name='transaction_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
