# Generated by Django 3.2.5 on 2023-01-25 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0010_alter_paymenttransactions_transaction_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymenttransactions',
            old_name='payment_provide',
            new_name='payment_provider',
        ),
    ]
