# Generated by Django 3.2.5 on 2023-01-25 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0011_rename_payment_provide_paymenttransactions_payment_provider'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='paymenttransactions',
            table=None,
        ),
    ]
