# Generated by Django 3.2.5 on 2023-01-25 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0012_alter_paymenttransactions_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'payment_methods',
            },
        ),
        migrations.AlterModelTable(
            name='paymenttransactions',
            table='payment_transactions',
        ),
    ]
