# Generated by Django 3.2.5 on 2023-01-25 17:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_alter_orders_order_id'),
        ('payment', '0013_auto_20230125_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethods',
            name='apple_pay',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paymentmethods',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_payment_method', to='orders.orders'),
        ),
        migrations.AddField(
            model_name='paymentmethods',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='country_payment_method', to='orders.orders'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentmethods',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentmethods',
            name='credit_card',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paymentmethods',
            name='credit_points',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paymentmethods',
            name='debit_card',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paymentmethods',
            name='paypal',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paymentmethods',
            name='provider',
            field=models.CharField(choices=[('1', 'USER'), ('2', 'SELLER')], default='1', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentmethods',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_payment_method', to='orders.orders'),
        ),
        migrations.AddField(
            model_name='paymentmethods',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='paymenttransactions',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('1', 'DEBIT_CARD'), ('2', 'CREDIT_CARD'), ('3', 'APPLE_PAY'), ('4', 'CREDIT_POINTS')], max_length=50, null=True),
        ),
    ]
