# Generated by Django 3.2.5 on 2023-01-26 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_savecountry_user'),
        ('payment', '0014_auto_20230125_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethods',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='city_payment_method', to='account.city'),
        ),
        migrations.AlterField(
            model_name='paymentmethods',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='country_payment_method', to='account.country'),
        ),
        migrations.AlterField(
            model_name='paymentmethods',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='state_payment_method', to='account.state'),
        ),
    ]
