# Generated by Django 3.2.5 on 2023-01-26 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_savecountry_user'),
        ('payment', '0015_auto_20230126_1714'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paymentmethods',
            unique_together={('country', 'state', 'city', 'provider')},
        ),
    ]
