# Generated by Django 3.2.5 on 2023-01-26 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_savecountry_user'),
        ('payment', '0016_alter_paymentmethods_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='paymentmethods',
            unique_together={('country', 'city', 'provider')},
        ),
    ]
