# Generated by Django 3.2.5 on 2023-01-26 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0017_alter_paymentmethods_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethods',
            name='paypal',
        ),
    ]
