# Generated by Django 3.2.5 on 2023-01-28 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0018_remove_paymentmethods_paypal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercreditpoint',
            name='user',
        ),
        migrations.RemoveField(
            model_name='paymenttransactions',
            name='credit_point_transaction_id',
        ),
        migrations.AddField(
            model_name='paymenttransactions',
            name='amount_paid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CreditPointTransaction',
        ),
        migrations.DeleteModel(
            name='UserCreditPoint',
        ),
    ]
