# Generated by Django 3.2.5 on 2023-02-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0019_auto_20230128_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethods',
            name='city',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
