# Generated by Django 3.2.5 on 2023-03-25 18:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=40)),
                ('is_reported', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('group_icon', models.CharField(blank=True, max_length=1000, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_group', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_group',
            },
        ),
        migrations.CreateModel(
            name='UserChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('is_reported', models.BooleanField(default=False)),
                ('chat_init_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_chat_initiator', to=settings.AUTH_USER_MODEL)),
                ('second_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_chat_second', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_chat_history',
            },
        ),
        migrations.CreateModel(
            name='UserAudioVideoCallHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(blank=True, max_length=50, null=True)),
                ('end_time', models.CharField(blank=True, max_length=50, null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('group_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.chatgroup')),
                ('receiver', models.ManyToManyField(blank=True, related_name='call_receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_audio_video_call_history',
            },
        ),
        migrations.CreateModel(
            name='MemberInChatGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_accept', models.BooleanField(default=False)),
                ('chat_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatgroup')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'members_in_chat_group',
            },
        ),
        migrations.AddField(
            model_name='chatgroup',
            name='members',
            field=models.ManyToManyField(related_name='chat_group_members', through='chat.MemberInChatGroup', to=settings.AUTH_USER_MODEL),
        ),
    ]
