# Generated by Django 3.2.5 on 2023-03-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatgroup',
            name='group_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
