# Generated by Django 3.2.5 on 2023-03-27 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatgroup_group_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraudiovideocallhistory',
            old_name='receiver',
            new_name='receivers',
        ),
    ]
