# Generated by Django 3.2.5 on 2023-03-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_receiver_useraudiovideocallhistory_receivers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatgroup',
            old_name='admin_name',
            new_name='admin_id',
        ),
        migrations.RemoveField(
            model_name='chatgroup',
            name='group_icon',
        ),
        migrations.AlterField(
            model_name='chatgroup',
            name='group_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
