# Generated by Django 3.2.5 on 2023-03-29 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20230328_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userchathistory',
            old_name='created_date',
            new_name='created_at',
        ),
    ]
