# Generated by Django 3.2.5 on 2023-03-31 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_rename_created_date_userchathistory_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraudiovideocallhistory',
            name='group_id',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
