# Generated by Django 3.2.5 on 2023-04-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_useraudiovideocallhistory_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraudiovideocallhistory',
            name='call_type',
            field=models.CharField(choices=[('1', 'AUDIO'), ('2', 'VIDEO')], default='1', max_length=20),
        ),
    ]
